In [1]:
import numpy as np
import pandas as pd

In [22]:
df = pd.read_csv('example.csv')

In [4]:
df.head(3)

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287

In [7]:
df.columns

Index(['Index', 'Organization Id', 'Name', 'Website', 'Country', 'Description',
       'Founded', 'Industry', 'Number of employees'],
      dtype='object')

In [14]:
df.iloc[:5]

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870

In [15]:
df.sort_values('Number of employees',ascending = False)

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
37,38,19E3a5Bf6dBDc4F,Cuevas-Moss,https://dodson-castaneda.net/,Guatemala,Extended human-resource intranet,1994,Music,9995
9,10,738b5aDe6B1C6A5,Gaines Inc,http://sandoval-hooper.com/,Uzbekistan,Multi-lateral scalable protocol,1997,Outsourcing / Offshoring,9698
47,48,49aECbDaE6aBD53,"Wallace, Madden and Morris",http://www.blevins-fernandez.biz/,Germany,Persistent real-time customer loyalty,2016,Pharmaceuticals,9443
63,64,055ffEfB2Dd95B0,Riley Ltd,http://wiley.com/,Brazil,Optional exuding superstructure,1986,Textiles,9315
61,62,EB9f456e8b7022a,Soto Group,https://norris.info/,Vietnam,Enterprise-wide executive installation,1988,Business Supplies / Equipment,9097
...,...,...,...,...,...,...,...,...,...
69,70,902D7Ac8b6d476b,Newton Inc,https://www.richmond-manning.info/,Netherlands Antilles,Fundamental stable info-mediaries,1976,Military Industry,563
30,31,ccBcC32adcbc530,"Sloan, Mays and Whitehead",http://lawson.com/,Chad,Face-to-face high-level conglomeration,1997,Civil Engineering,365
60,61,bD1bc6bB6d1FeD3,Freeman-Chen,https://mathis.com/,Timor-Leste,Phased next generation adapter,1973,International Trade / Development,346
98,99,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
97,98,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236

In [23]:
df = df.drop('Organization Id', axis = 1)

In [26]:
df['Country'].value_counts()

Country
Benin                           3
Sweden                          3
Northern Mariana Islands        2
United States Virgin Islands    2
Eritrea                         2
                               ..
Philippines                     1
Christmas Island                1
Czech Republic                  1
Romania                         1
Anguilla                        1
Name: count, Length: 84, dtype: int64

In [27]:
df['Country'].unique()

array(['Papua New Guinea', 'Finland', 'China', 'Turkmenistan',
       'Mauritius', 'Bahamas', 'Pakistan',
       'Heard Island and McDonald Islands', 'Kuwait', 'Uzbekistan',
       'Bouvet Island (Bouvetoya)', 'Denmark', 'Liberia',
       'United Arab Emirates', 'Sweden', 'Honduras', 'Uganda',
       'Hong Kong', 'Botswana', 'Korea', 'Luxembourg', 'Guadeloupe',
       'Monaco', 'Belgium', 'South Africa', 'Romania', 'Czech Republic',
       'Christmas Island', 'Philippines', 'Australia', 'Chad', 'Zimbabwe',
       'Nepal', 'Taiwan', 'Kyrgyz Republic', 'Bolivia', 'Kenya',
       'Guatemala', 'Belarus', 'Jersey', 'Grenada', 'Cape Verde',
       'Trinidad and Tobago', 'Benin', 'Western Sahara',
       'Northern Mariana Islands', 'Germany', 'Canada', 'Tonga',
       'French Southern Territories', "Cote d'Ivoire", 'Mayotte',
       'Cayman Islands', 'Nigeria', 'Marshall Islands', 'Palau', 'Turkey',
       'Timor-Leste', 'Vietnam', 'Reunion', 'Brazil', 'Eritrea',
       'United States Virgin Islands', 'Falkland Islands (Malvinas)',
       'Netherlands Antilles', 'Guernsey', 'Uruguay', 'Suriname',
       'Mongolia', 'Svalbard & Jan Mayen Islands', 'Togo', 'Latvia',
       'Cuba', 'Liechtenstein', 'Djibouti', 'Micronesia', 'Cameroon',
       'Cocos (Keeling) Islands', 'Mali', 'Burundi', 'Gibraltar',
       'El Salvador', 'Ethiopia', 'Anguilla'], dtype=object)

In [28]:
df['Country'].replace('China','India')

0                Papua New Guinea
1                         Finland
2                           India
3                    Turkmenistan
4                       Mauritius
                 ...
95                       Ethiopia
96                       Anguilla
97    Falkland Islands (Malvinas)
98                Kyrgyz Republic
99                           Togo
Name: Country, Length: 100, dtype: object