In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

In [4]:
myindex = ['MH', 'KN', 'TN', 'WB']

In [5]:
print(mydata)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]

In [6]:
attr = ['GDP', 'IT', 'REL']

In [7]:
df = pd.DataFrame(mydata)

In [8]:
df

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [9]:
pndf = pd.DataFrame(mydata, myindex, attr)

In [10]:
pndf

    GDP  IT  REL
MH   95  11   81
KN   70  63   87
TN   75   9   77
WB   40   4   63

In [11]:
pndf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, MH to WB
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GDP     4 non-null      int32
 1   IT      4 non-null      int32
 2   REL     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [12]:
df1 = pd.read_csv('example.csv')

In [13]:
df1

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870
...,...,...,...,...,...,...,...,...,...
95,96,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
96,97,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
97,98,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
98,99,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
99,100,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

In [14]:
df2 = pd.read_csv('C:\\Users\\prana\\Jupyter\\Python\\IndiaData.csv')

In [15]:
df2

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.027104,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN
1,IND,India,Indian Rupee,1980,5.281000,0.023364,11.346060,0.007102,0.038942,-0.032347,...,0.311639,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281000
2,IND,India,Indian Rupee,1981,6.006000,0.023510,13.112550,0.004508,-0.027032,0.101181,...,0.171218,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006000
3,IND,India,Indian Rupee,1982,3.476000,0.023560,7.890750,0.004125,-0.013325,0.092003,...,-0.227116,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476000
4,IND,India,Indian Rupee,1983,7.289000,0.023475,11.868070,0.003785,0.016143,0.068086,...,0.568956,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289000
5,IND,India,Indian Rupee,1984,3.821000,0.023224,8.318914,0.003513,-0.004469,0.125131,...,-0.186774,0.311368,-0.020696,0.066587,0.043739,-0.000758,0.161264,0.079760,-0.070062,3.821000
6,IND,India,Indian Rupee,1985,5.254000,0.022856,5.556426,0.003255,-0.023227,0.088551,...,0.100199,-0.152234,-0.007321,0.094918,0.061442,0.020255,0.002747,0.070623,0.027706,5.254000
7,IND,India,Indian Rupee,1986,4.777000,0.022458,8.729712,0.004868,-0.004420,0.019572,...,-0.186842,0.336192,0.056895,0.023806,0.071507,0.109075,0.139978,0.046031,0.037279,4.777000
8,IND,India,Indian Rupee,1987,3.965000,0.022079,8.801135,0.004824,0.004842,0.027807,...,-0.076174,0.281138,0.037346,0.049373,0.073591,0.086690,0.121913,0.100678,0.039696,3.965000
9,IND,India,Indian Rupee,1988,9.628000,0.021700,9.383466,0.004898,-0.003169,0.073725,...,0.005041,-0.108235,0.009976,0.015035,0.039840,0.077601,0.038810,0.025516,0.031666,9.628000
10,IND,India,Indian Rupee,1989,5.947000,0.021333,7.074283,0.004862,-0.021076,0.165869,...,0.013185,-0.173991,-0.099747,-0.049723,-0.056037,0.035812,0.032925,-0.056711,-0.089863,5.947000
11,IND,India,Indian Rupee,1990,5.534000,0.020978,8.971233,0.004829,-0.003241,0.078765,...,-0.032025,0.232349,-0.014930,0.013010,0.102894,0.010641,0.062956,-0.018995,-0.006948,5.534000
12,IND,India,Indian Rupee,1991,1.057000,0.020607,13.870250,0.004544,-0.005890,0.299308,...,-0.223736,-0.761933,-0.139573,-0.135302,-0.112119,0.048380,0.023387,-0.124870,-0.159818,1.057000
13,IND,India,Indian Rupee,1992,5.482000,0.020234,11.787820,0.005020,-0.009426,0.139635,...,0.263393,-0.726045,-0.041800,-0.079158,-0.026472,-0.090891,-0.060410,-0.083286,-0.060208,5.482000
14,IND,India,Indian Rupee,1993,4.750000,0.019902,6.326890,0.005741,-0.020890,0.176526,...,-0.043973,-0.713174,-0.073873,-0.103853,-0.041037,0.009653,-0.052511,-0.082276,-0.074398,4.750000
15,IND,India,Indian Rupee,1994,6.659000,0.019622,10.247930,-0.005355,-0.021239,0.028874,...,0.131909,13.876584,0.067011,0.072049,0.082658,0.001764,0.028131,0.039393,0.060490,6.659000
16,IND,India,Indian Rupee,1995,7.575000,0.019375,10.224890,-0.008672,-0.026847,0.033574,...,0.102384,-0.796965,0.032045,0.084924,0.095815,0.086796,0.070486,0.066183,0.091477,7.575000
17,IND,India,Indian Rupee,1996,7.550000,0.019133,8.977149,-0.008022,-0.001592,0.092703,...,0.013307,-4.453907,-0.020633,-0.017259,0.041420,0.010158,-0.021668,-0.028629,-0.033104,7.550000
18,IND,India,Indian Rupee,1997,4.050000,0.018868,7.164254,-0.006938,-0.001218,0.024839,...,0.060998,-2.130750,0.042917,-0.007596,0.012639,-0.042549,-0.043428,0.011598,-0.020075,4.050000
19,IND,India,Indian Rupee,1998,6.184000,0.018567,13.230840,-0.006260,-0.019013,0.136206,...,-0.003046,-1.228907,-0.050186,-0.099545,-0.035399,-0.059402,-0.050400,-0.099419,-0.022218,6.184000
20,IND,India,Indian Rupee,1999,8.463000,0.018220,4.669821,-0.005212,-0.014016,0.043531,...,0.103303,-10.032102,0.011703,-0.026073,-0.022857,-0.018184,-0.004329,-0.024019,-0.025468,8.463000
21,IND,India,Indian Rupee,2000,3.975000,0.017838,4.009434,0.004469,-0.011311,0.043808,...,0.074086,-1.132325,-0.008009,-0.052760,-0.007003,-0.006370,-0.060729,-0.047471,-0.024881,3.975000
22,IND,India,Indian Rupee,2001,4.944000,0.017438,3.779289,0.008110,-0.020530,0.049949,...,-0.055377,-3.627981,-0.026366,-0.056689,-0.013667,-0.021244,-0.041409,-0.066053,-0.037954,4.944000
23,IND,India,Indian Rupee,2002,3.907000,0.017039,4.297160,0.008945,-0.042768,0.030176,...,0.067324,-1.417425,-0.006589,-0.056503,0.010513,0.014669,0.003929,-0.052138,-0.049207,3.907000
24,IND,India,Indian Rupee,2003,7.944000,0.016652,3.805866,0.010220,-0.014260,-0.041700,...,0.038317,1.457045,0.072527,0.070368,0.068049,0.092783,0.113291,0.051080,0.018894,7.944000
25,IND,India,Indian Rupee,2004,7.849000,0.016284,3.767238,0.011032,-0.065614,-0.027195,...,0.187111,-1.869947,0.053002,0.086684,0.065511,0.087538,0.053750,0.116882,0.077307,7.849000
26,IND,India,Indian Rupee,2005,9.285000,0.015923,4.246353,-0.008975,-0.025924,-0.026844,...,0.178544,-2.203960,0.047061,-0.020539,0.042907,0.009240,0.049776,0.005761,-0.019922,9.285000
27,IND,India,Indian Rupee,2006,9.264000,0.015577,5.796516,-0.014616,-0.037970,0.027370,...,0.078239,4.146212,0.035373,0.014385,0.053896,0.034312,0.050826,-0.032519,0.006624,9.264000
28,IND,India,Indian Rupee,2007,9.801000,0.015207,6.372881,-0.012709,-0.002566,-0.087370,...,0.026283,-0.662455,0.130622,0.097250,0.170924,0.098637,0.075467,0.088029,0.079779,9.801000
29,IND,India,Indian Rupee,2008,6.013703,0.014757,8.349267,-0.010712,0.043023,0.052158,...,0.258178,2.560328,0.000677,0.103498,0.037898,0.102812,0.079440,-0.021167,-0.107610,6.013703
30,IND,India,Indian Rupee,2009,4.701769,0.014206,10.882350,-0.007974,0.018861,0.112632,...,-0.113538,-0.900952,-0.052353,-0.081272,0.000161,-0.059148,-0.110411,-0.104797,-0.126488,4.701769
31,IND,India,Indian Rupee,2010,6.377626,0.013595,11.989390,-0.005369,-0.000465,-0.055355,...,0.079773,3.576668,0.118745,0.067262,0.162277,0.035864,0.058451,0.060201,0.061474,6.377626
32,IND,India,Indian Rupee,2011,6.169784,0.012968,8.858361,-0.002660,0.002810,0.020659,...,0.149702,-0.241803,0.031373,0.051464,0.048572,0.041912,0.057688,0.046285,-0.004046,6.169784
33,IND,India,Indian Rupee,2012,6.030051,0.012391,9.312446,-0.017225,-0.001126,0.144990,...,0.007833,2.026501,-0.079003,-0.051365,-0.078201,-0.014858,-0.032542,-0.055971,-0.072460,6.030051
34,IND,India,Indian Rupee,2013,5.557264,0.011899,10.907640,0.017737,0.008968,0.096573,...,-0.093159,-0.083955,0.005785,0.000298,0.081144,0.037289,0.045635,-0.029470,-0.033451,5.557264
35,IND,India,Indian Rupee,2014,5.006668,0.011523,6.353195,-0.012964,-0.000523,0.041498,...,-0.091486,-0.146804,0.022496,0.019665,0.115143,0.017622,0.044393,0.014433,0.007264,5.006668
36,IND,India,Indian Rupee,2015,4.876322,0.011232,5.872427,-0.011893,-0.016322,0.051163,...,-0.095621,0.066051,-0.009829,-0.023410,0.081454,-0.088196,-0.104489,-0.033910,0.014187,4.876322
37,IND,India,Indian Rupee,2016,5.033069,0.010964,4.941027,-0.010254,0.020103,0.047438,...,-0.134412,-0.388348,-0.002899,-0.000481,0.098854,-0.009819,0.001580,-0.009982,-0.018257,5.033069
38,IND,India,Indian Rupee,2017,5.069786,0.010690,2.490887,-0.001969,0.008309,-0.030860,...,0.170865,-0.349163,0.080693,0.065260,0.144193,0.021018,0.001887,0.087036,0.051854,5.069786
39,IND,India,Indian Rupee,2018,5.174292,0.010432,4.860700,-0.002430,0.000000,0.050310,...,0.016755,1.354393,-0.008446,0.001625,-0.016725,0.046373,0.048705,-0.003372,-0.052542,5.174292
40,IND,India,Indian Rupee,2019,5.019288,0.010184,7.659695,0.003099,0.000000,0.029564,...,-0.097739,-0.170348,0.015769,-0.006184,0.009944,0.020876,0.015795,-0.010301,-0.019226,5.019288

In [16]:
df2.columns

Index(['countrycode', 'country', 'currency_unit', 'year', 'GDP',
       'net population growth', 'CPI', 'employment rate', 'labsh', 'xr',
       'pl_gdpo', 'csh_c', 'csh_i', 'csh_g', 'csh_x', 'csh_m', 'csh_r', 'pl_c',
       'pl_i', 'pl_g', 'pl_x', 'pl_m', 'pl_n', 'pl_k', 'GDP.1'],
      dtype='object')

In [17]:
df2.index

RangeIndex(start=0, stop=41, step=1)

In [18]:
df2.head(10)

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.027104,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN
1,IND,India,Indian Rupee,1980,5.281,0.023364,11.346060,0.007102,0.038942,-0.032347,...,0.311639,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281
2,IND,India,Indian Rupee,1981,6.006,0.023510,13.112550,0.004508,-0.027032,0.101181,...,0.171218,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006
3,IND,India,Indian Rupee,1982,3.476,0.023560,7.890750,0.004125,-0.013325,0.092003,...,-0.227116,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476
4,IND,India,Indian Rupee,1983,7.289,0.023475,11.868070,0.003785,0.016143,0.068086,...,0.568956,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289
5,IND,India,Indian Rupee,1984,3.821,0.023224,8.318914,0.003513,-0.004469,0.125131,...,-0.186774,0.311368,-0.020696,0.066587,0.043739,-0.000758,0.161264,0.079760,-0.070062,3.821
6,IND,India,Indian Rupee,1985,5.254,0.022856,5.556426,0.003255,-0.023227,0.088551,...,0.100199,-0.152234,-0.007321,0.094918,0.061442,0.020255,0.002747,0.070623,0.027706,5.254
7,IND,India,Indian Rupee,1986,4.777,0.022458,8.729712,0.004868,-0.004420,0.019572,...,-0.186842,0.336192,0.056895,0.023806,0.071507,0.109075,0.139978,0.046031,0.037279,4.777
8,IND,India,Indian Rupee,1987,3.965,0.022079,8.801135,0.004824,0.004842,0.027807,...,-0.076174,0.281138,0.037346,0.049373,0.073591,0.086690,0.121913,0.100678,0.039696,3.965
9,IND,India,Indian Rupee,1988,9.628,0.021700,9.383466,0.004898,-0.003169,0.073725,...,0.005041,-0.108235,0.009976,0.015035,0.039840,0.077601,0.038810,0.025516,0.031666,9.628

In [19]:
df2.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
year,41.0,1999.000000,11.979149,1979.000000,1989.000000,1999.000000,2009.000000,2019.000000
GDP,40.0,5.868666,1.854317,1.057000,4.851492,5.508000,6.816500,9.801000
net population growth,41.0,16.675493,106.663221,0.010184,0.014206,0.018220,0.021333,682.995354
CPI,40.0,7.902614,3.043830,2.490887,5.402576,8.104832,10.230650,13.870250
employment rate,41.0,6.263619,40.111651,-0.017225,-0.007974,0.003255,0.004868,256.839111
labsh,41.0,0.010039,0.113658,-0.065614,-0.020530,-0.004420,0.000000,0.709059
xr,41.0,0.254593,1.262023,-0.087370,0.027370,0.049949,0.096573,8.125791
pl_gdpo,41.0,0.021244,0.065271,-0.142609,-0.014644,0.017332,0.050503,0.191659
csh_c,41.0,0.015728,0.106977,-0.044591,-0.010980,-0.001110,0.015361,0.672914
csh_i,41.0,0.018882,0.081396,-0.169636,-0.034339,0.003695,0.085581,0.197984
csh_g,41.0,-0.020405,0.059846,-0.100470,-0.054674,-0.029993,0.010016,0.224698
csh_x,41.0,0.019582,0.080035,-0.132554,-0.030599,0.010718,0.063934,0.209711
csh_m,41.0,0.036352,0.156437,-0.227116,-0.076174,0.016755,0.103303,0.568956
csh_r,41.0,-0.115497,3.134763,-10.032102,-0.796965,-0.235969,0.281138,13.876584
pl_c,41.0,0.017192,0.068757,-0.139573,-0.014930,0.011703,0.042917,0.221119
pl_i,41.0,0.019181,0.077100,-0.135302,-0.026073,0.014385,0.067262,0.224667
pl_g,41.0,0.050118,0.069892,-0.112119,0.000161,0.053896,0.090714,0.211470
pl_x,41.0,0.029594,0.064973,-0.090891,-0.000758,0.020876,0.062000,0.292258
pl_m,41.0,0.025775,0.088399,-0.117499,-0.032542,0.028131,0.058451,0.374884
pl_n,41.0,0.015990,0.077446,-0.124870,-0.033910,0.005761,0.070623,0.198038
pl_k,41.0,0.005179,0.114807,-0.159818,-0.044686,-0.018257,0.039696,0.623519
GDP.1,40.0,5.868666,1.854317,1.057000,4.851492,5.508000,6.816500,9.801000

In [20]:
arr = np.arange(0,25,1).reshape(5,5).transpose()

In [21]:
print(arr)

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]

In [22]:
df2.head(7)

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.027104,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN
1,IND,India,Indian Rupee,1980,5.281,0.023364,11.346060,0.007102,0.038942,-0.032347,...,0.311639,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281
2,IND,India,Indian Rupee,1981,6.006,0.023510,13.112550,0.004508,-0.027032,0.101181,...,0.171218,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006
3,IND,India,Indian Rupee,1982,3.476,0.023560,7.890750,0.004125,-0.013325,0.092003,...,-0.227116,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476
4,IND,India,Indian Rupee,1983,7.289,0.023475,11.868070,0.003785,0.016143,0.068086,...,0.568956,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289
5,IND,India,Indian Rupee,1984,3.821,0.023224,8.318914,0.003513,-0.004469,0.125131,...,-0.186774,0.311368,-0.020696,0.066587,0.043739,-0.000758,0.161264,0.079760,-0.070062,3.821
6,IND,India,Indian Rupee,1985,5.254,0.022856,5.556426,0.003255,-0.023227,0.088551,...,0.100199,-0.152234,-0.007321,0.094918,0.061442,0.020255,0.002747,0.070623,0.027706,5.254

In [23]:
col = ['year', 'GDP']

In [24]:
df2[col]

    year       GDP
0   1979       NaN
1   1980  5.281000
2   1981  6.006000
3   1982  3.476000
4   1983  7.289000
5   1984  3.821000
6   1985  5.254000
7   1986  4.777000
8   1987  3.965000
9   1988  9.628000
10  1989  5.947000
11  1990  5.534000
12  1991  1.057000
13  1992  5.482000
14  1993  4.750000
15  1994  6.659000
16  1995  7.575000
17  1996  7.550000
18  1997  4.050000
19  1998  6.184000
20  1999  8.463000
21  2000  3.975000
22  2001  4.944000
23  2002  3.907000
24  2003  7.944000
25  2004  7.849000
26  2005  9.285000
27  2006  9.264000
28  2007  9.801000
29  2008  6.013703
30  2009  4.701769
31  2010  6.377626
32  2011  6.169784
33  2012  6.030051
34  2013  5.557264
35  2014  5.006668
36  2015  4.876322
37  2016  5.033069
38  2017  5.069786
39  2018  5.174292
40  2019  5.019288

In [25]:
0.5 * (df2['GDP'] + df2['GDP.1'])

0          NaN
1     5.281000
2     6.006000
3     3.476000
4     7.289000
5     3.821000
6     5.254000
7     4.777000
8     3.965000
9     9.628000
10    5.947000
11    5.534000
12    1.057000
13    5.482000
14    4.750000
15    6.659000
16    7.575000
17    7.550000
18    4.050000
19    6.184000
20    8.463000
21    3.975000
22    4.944000
23    3.907000
24    7.944000
25    7.849000
26    9.285000
27    9.264000
28    9.801000
29    6.013703
30    4.701769
31    6.377626
32    6.169784
33    6.030051
34    5.557264
35    5.006668
36    4.876322
37    5.033069
38    5.069786
39    5.174292
40    5.019288
dtype: float64

In [26]:
df2['Percent_max'] = 100 * df2['GDP'] / df2['GDP'].max()

In [27]:
df2.head()

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1,Percent_max
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN,NaN
1,IND,India,Indian Rupee,1980,5.281,0.023364,11.34606,0.007102,0.038942,-0.032347,...,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281,53.882257
2,IND,India,Indian Rupee,1981,6.006,0.023510,13.11255,0.004508,-0.027032,0.101181,...,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006,61.279461
3,IND,India,Indian Rupee,1982,3.476,0.023560,7.89075,0.004125,-0.013325,0.092003,...,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476,35.465769
4,IND,India,Indian Rupee,1983,7.289,0.023475,11.86807,0.003785,0.016143,0.068086,...,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289,74.369962

In [28]:
df2['Percent_max'] = np.round( df2['GDP'] / df2['GDP'].max(), decimals = 2)

In [29]:
df2.head()

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1,Percent_max
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN,NaN
1,IND,India,Indian Rupee,1980,5.281,0.023364,11.34606,0.007102,0.038942,-0.032347,...,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281,0.54
2,IND,India,Indian Rupee,1981,6.006,0.023510,13.11255,0.004508,-0.027032,0.101181,...,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006,0.61
3,IND,India,Indian Rupee,1982,3.476,0.023560,7.89075,0.004125,-0.013325,0.092003,...,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476,0.35
4,IND,India,Indian Rupee,1983,7.289,0.023475,11.86807,0.003785,0.016143,0.068086,...,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289,0.74

In [30]:
df2['Percent_max'] *=100

In [31]:
df2.head()

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1,Percent_max
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN,NaN
1,IND,India,Indian Rupee,1980,5.281,0.023364,11.34606,0.007102,0.038942,-0.032347,...,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281,54.0
2,IND,India,Indian Rupee,1981,6.006,0.023510,13.11255,0.004508,-0.027032,0.101181,...,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006,61.0
3,IND,India,Indian Rupee,1982,3.476,0.023560,7.89075,0.004125,-0.013325,0.092003,...,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476,35.0
4,IND,India,Indian Rupee,1983,7.289,0.023475,11.86807,0.003785,0.016143,0.068086,...,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289,74.0

In [32]:
#removing column
df2.drop('Percent_max',axis = 1)

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.027104,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN
1,IND,India,Indian Rupee,1980,5.281000,0.023364,11.346060,0.007102,0.038942,-0.032347,...,0.311639,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281000
2,IND,India,Indian Rupee,1981,6.006000,0.023510,13.112550,0.004508,-0.027032,0.101181,...,0.171218,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006000
3,IND,India,Indian Rupee,1982,3.476000,0.023560,7.890750,0.004125,-0.013325,0.092003,...,-0.227116,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476000
4,IND,India,Indian Rupee,1983,7.289000,0.023475,11.868070,0.003785,0.016143,0.068086,...,0.568956,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289000
5,IND,India,Indian Rupee,1984,3.821000,0.023224,8.318914,0.003513,-0.004469,0.125131,...,-0.186774,0.311368,-0.020696,0.066587,0.043739,-0.000758,0.161264,0.079760,-0.070062,3.821000
6,IND,India,Indian Rupee,1985,5.254000,0.022856,5.556426,0.003255,-0.023227,0.088551,...,0.100199,-0.152234,-0.007321,0.094918,0.061442,0.020255,0.002747,0.070623,0.027706,5.254000
7,IND,India,Indian Rupee,1986,4.777000,0.022458,8.729712,0.004868,-0.004420,0.019572,...,-0.186842,0.336192,0.056895,0.023806,0.071507,0.109075,0.139978,0.046031,0.037279,4.777000
8,IND,India,Indian Rupee,1987,3.965000,0.022079,8.801135,0.004824,0.004842,0.027807,...,-0.076174,0.281138,0.037346,0.049373,0.073591,0.086690,0.121913,0.100678,0.039696,3.965000
9,IND,India,Indian Rupee,1988,9.628000,0.021700,9.383466,0.004898,-0.003169,0.073725,...,0.005041,-0.108235,0.009976,0.015035,0.039840,0.077601,0.038810,0.025516,0.031666,9.628000
10,IND,India,Indian Rupee,1989,5.947000,0.021333,7.074283,0.004862,-0.021076,0.165869,...,0.013185,-0.173991,-0.099747,-0.049723,-0.056037,0.035812,0.032925,-0.056711,-0.089863,5.947000
11,IND,India,Indian Rupee,1990,5.534000,0.020978,8.971233,0.004829,-0.003241,0.078765,...,-0.032025,0.232349,-0.014930,0.013010,0.102894,0.010641,0.062956,-0.018995,-0.006948,5.534000
12,IND,India,Indian Rupee,1991,1.057000,0.020607,13.870250,0.004544,-0.005890,0.299308,...,-0.223736,-0.761933,-0.139573,-0.135302,-0.112119,0.048380,0.023387,-0.124870,-0.159818,1.057000
13,IND,India,Indian Rupee,1992,5.482000,0.020234,11.787820,0.005020,-0.009426,0.139635,...,0.263393,-0.726045,-0.041800,-0.079158,-0.026472,-0.090891,-0.060410,-0.083286,-0.060208,5.482000
14,IND,India,Indian Rupee,1993,4.750000,0.019902,6.326890,0.005741,-0.020890,0.176526,...,-0.043973,-0.713174,-0.073873,-0.103853,-0.041037,0.009653,-0.052511,-0.082276,-0.074398,4.750000
15,IND,India,Indian Rupee,1994,6.659000,0.019622,10.247930,-0.005355,-0.021239,0.028874,...,0.131909,13.876584,0.067011,0.072049,0.082658,0.001764,0.028131,0.039393,0.060490,6.659000
16,IND,India,Indian Rupee,1995,7.575000,0.019375,10.224890,-0.008672,-0.026847,0.033574,...,0.102384,-0.796965,0.032045,0.084924,0.095815,0.086796,0.070486,0.066183,0.091477,7.575000
17,IND,India,Indian Rupee,1996,7.550000,0.019133,8.977149,-0.008022,-0.001592,0.092703,...,0.013307,-4.453907,-0.020633,-0.017259,0.041420,0.010158,-0.021668,-0.028629,-0.033104,7.550000
18,IND,India,Indian Rupee,1997,4.050000,0.018868,7.164254,-0.006938,-0.001218,0.024839,...,0.060998,-2.130750,0.042917,-0.007596,0.012639,-0.042549,-0.043428,0.011598,-0.020075,4.050000
19,IND,India,Indian Rupee,1998,6.184000,0.018567,13.230840,-0.006260,-0.019013,0.136206,...,-0.003046,-1.228907,-0.050186,-0.099545,-0.035399,-0.059402,-0.050400,-0.099419,-0.022218,6.184000
20,IND,India,Indian Rupee,1999,8.463000,0.018220,4.669821,-0.005212,-0.014016,0.043531,...,0.103303,-10.032102,0.011703,-0.026073,-0.022857,-0.018184,-0.004329,-0.024019,-0.025468,8.463000
21,IND,India,Indian Rupee,2000,3.975000,0.017838,4.009434,0.004469,-0.011311,0.043808,...,0.074086,-1.132325,-0.008009,-0.052760,-0.007003,-0.006370,-0.060729,-0.047471,-0.024881,3.975000
22,IND,India,Indian Rupee,2001,4.944000,0.017438,3.779289,0.008110,-0.020530,0.049949,...,-0.055377,-3.627981,-0.026366,-0.056689,-0.013667,-0.021244,-0.041409,-0.066053,-0.037954,4.944000
23,IND,India,Indian Rupee,2002,3.907000,0.017039,4.297160,0.008945,-0.042768,0.030176,...,0.067324,-1.417425,-0.006589,-0.056503,0.010513,0.014669,0.003929,-0.052138,-0.049207,3.907000
24,IND,India,Indian Rupee,2003,7.944000,0.016652,3.805866,0.010220,-0.014260,-0.041700,...,0.038317,1.457045,0.072527,0.070368,0.068049,0.092783,0.113291,0.051080,0.018894,7.944000
25,IND,India,Indian Rupee,2004,7.849000,0.016284,3.767238,0.011032,-0.065614,-0.027195,...,0.187111,-1.869947,0.053002,0.086684,0.065511,0.087538,0.053750,0.116882,0.077307,7.849000
26,IND,India,Indian Rupee,2005,9.285000,0.015923,4.246353,-0.008975,-0.025924,-0.026844,...,0.178544,-2.203960,0.047061,-0.020539,0.042907,0.009240,0.049776,0.005761,-0.019922,9.285000
27,IND,India,Indian Rupee,2006,9.264000,0.015577,5.796516,-0.014616,-0.037970,0.027370,...,0.078239,4.146212,0.035373,0.014385,0.053896,0.034312,0.050826,-0.032519,0.006624,9.264000
28,IND,India,Indian Rupee,2007,9.801000,0.015207,6.372881,-0.012709,-0.002566,-0.087370,...,0.026283,-0.662455,0.130622,0.097250,0.170924,0.098637,0.075467,0.088029,0.079779,9.801000
29,IND,India,Indian Rupee,2008,6.013703,0.014757,8.349267,-0.010712,0.043023,0.052158,...,0.258178,2.560328,0.000677,0.103498,0.037898,0.102812,0.079440,-0.021167,-0.107610,6.013703
30,IND,India,Indian Rupee,2009,4.701769,0.014206,10.882350,-0.007974,0.018861,0.112632,...,-0.113538,-0.900952,-0.052353,-0.081272,0.000161,-0.059148,-0.110411,-0.104797,-0.126488,4.701769
31,IND,India,Indian Rupee,2010,6.377626,0.013595,11.989390,-0.005369,-0.000465,-0.055355,...,0.079773,3.576668,0.118745,0.067262,0.162277,0.035864,0.058451,0.060201,0.061474,6.377626
32,IND,India,Indian Rupee,2011,6.169784,0.012968,8.858361,-0.002660,0.002810,0.020659,...,0.149702,-0.241803,0.031373,0.051464,0.048572,0.041912,0.057688,0.046285,-0.004046,6.169784
33,IND,India,Indian Rupee,2012,6.030051,0.012391,9.312446,-0.017225,-0.001126,0.144990,...,0.007833,2.026501,-0.079003,-0.051365,-0.078201,-0.014858,-0.032542,-0.055971,-0.072460,6.030051
34,IND,India,Indian Rupee,2013,5.557264,0.011899,10.907640,0.017737,0.008968,0.096573,...,-0.093159,-0.083955,0.005785,0.000298,0.081144,0.037289,0.045635,-0.029470,-0.033451,5.557264
35,IND,India,Indian Rupee,2014,5.006668,0.011523,6.353195,-0.012964,-0.000523,0.041498,...,-0.091486,-0.146804,0.022496,0.019665,0.115143,0.017622,0.044393,0.014433,0.007264,5.006668
36,IND,India,Indian Rupee,2015,4.876322,0.011232,5.872427,-0.011893,-0.016322,0.051163,...,-0.095621,0.066051,-0.009829,-0.023410,0.081454,-0.088196,-0.104489,-0.033910,0.014187,4.876322
37,IND,India,Indian Rupee,2016,5.033069,0.010964,4.941027,-0.010254,0.020103,0.047438,...,-0.134412,-0.388348,-0.002899,-0.000481,0.098854,-0.009819,0.001580,-0.009982,-0.018257,5.033069
38,IND,India,Indian Rupee,2017,5.069786,0.010690,2.490887,-0.001969,0.008309,-0.030860,...,0.170865,-0.349163,0.080693,0.065260,0.144193,0.021018,0.001887,0.087036,0.051854,5.069786
39,IND,India,Indian Rupee,2018,5.174292,0.010432,4.860700,-0.002430,0.000000,0.050310,...,0.016755,1.354393,-0.008446,0.001625,-0.016725,0.046373,0.048705,-0.003372,-0.052542,5.174292
40,IND,India,Indian Rupee,2019,5.019288,0.010184,7.659695,0.003099,0.000000,0.029564,...,-0.097739,-0.170348,0.015769,-0.006184,0.009944,0.020876,0.015795,-0.010301,-0.019226,5.019288

In [33]:
df2.drop(0)

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1,Percent_max
1,IND,India,Indian Rupee,1980,5.281000,0.023364,11.346060,0.007102,0.038942,-0.032347,...,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281000,54.0
2,IND,India,Indian Rupee,1981,6.006000,0.023510,13.112550,0.004508,-0.027032,0.101181,...,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006000,61.0
3,IND,India,Indian Rupee,1982,3.476000,0.023560,7.890750,0.004125,-0.013325,0.092003,...,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476000,35.0
4,IND,India,Indian Rupee,1983,7.289000,0.023475,11.868070,0.003785,0.016143,0.068086,...,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289000,74.0
5,IND,India,Indian Rupee,1984,3.821000,0.023224,8.318914,0.003513,-0.004469,0.125131,...,0.311368,-0.020696,0.066587,0.043739,-0.000758,0.161264,0.079760,-0.070062,3.821000,39.0
6,IND,India,Indian Rupee,1985,5.254000,0.022856,5.556426,0.003255,-0.023227,0.088551,...,-0.152234,-0.007321,0.094918,0.061442,0.020255,0.002747,0.070623,0.027706,5.254000,54.0
7,IND,India,Indian Rupee,1986,4.777000,0.022458,8.729712,0.004868,-0.004420,0.019572,...,0.336192,0.056895,0.023806,0.071507,0.109075,0.139978,0.046031,0.037279,4.777000,49.0
8,IND,India,Indian Rupee,1987,3.965000,0.022079,8.801135,0.004824,0.004842,0.027807,...,0.281138,0.037346,0.049373,0.073591,0.086690,0.121913,0.100678,0.039696,3.965000,40.0
9,IND,India,Indian Rupee,1988,9.628000,0.021700,9.383466,0.004898,-0.003169,0.073725,...,-0.108235,0.009976,0.015035,0.039840,0.077601,0.038810,0.025516,0.031666,9.628000,98.0
10,IND,India,Indian Rupee,1989,5.947000,0.021333,7.074283,0.004862,-0.021076,0.165869,...,-0.173991,-0.099747,-0.049723,-0.056037,0.035812,0.032925,-0.056711,-0.089863,5.947000,61.0
11,IND,India,Indian Rupee,1990,5.534000,0.020978,8.971233,0.004829,-0.003241,0.078765,...,0.232349,-0.014930,0.013010,0.102894,0.010641,0.062956,-0.018995,-0.006948,5.534000,56.0
12,IND,India,Indian Rupee,1991,1.057000,0.020607,13.870250,0.004544,-0.005890,0.299308,...,-0.761933,-0.139573,-0.135302,-0.112119,0.048380,0.023387,-0.124870,-0.159818,1.057000,11.0
13,IND,India,Indian Rupee,1992,5.482000,0.020234,11.787820,0.005020,-0.009426,0.139635,...,-0.726045,-0.041800,-0.079158,-0.026472,-0.090891,-0.060410,-0.083286,-0.060208,5.482000,56.0
14,IND,India,Indian Rupee,1993,4.750000,0.019902,6.326890,0.005741,-0.020890,0.176526,...,-0.713174,-0.073873,-0.103853,-0.041037,0.009653,-0.052511,-0.082276,-0.074398,4.750000,48.0
15,IND,India,Indian Rupee,1994,6.659000,0.019622,10.247930,-0.005355,-0.021239,0.028874,...,13.876584,0.067011,0.072049,0.082658,0.001764,0.028131,0.039393,0.060490,6.659000,68.0
16,IND,India,Indian Rupee,1995,7.575000,0.019375,10.224890,-0.008672,-0.026847,0.033574,...,-0.796965,0.032045,0.084924,0.095815,0.086796,0.070486,0.066183,0.091477,7.575000,77.0
17,IND,India,Indian Rupee,1996,7.550000,0.019133,8.977149,-0.008022,-0.001592,0.092703,...,-4.453907,-0.020633,-0.017259,0.041420,0.010158,-0.021668,-0.028629,-0.033104,7.550000,77.0
18,IND,India,Indian Rupee,1997,4.050000,0.018868,7.164254,-0.006938,-0.001218,0.024839,...,-2.130750,0.042917,-0.007596,0.012639,-0.042549,-0.043428,0.011598,-0.020075,4.050000,41.0
19,IND,India,Indian Rupee,1998,6.184000,0.018567,13.230840,-0.006260,-0.019013,0.136206,...,-1.228907,-0.050186,-0.099545,-0.035399,-0.059402,-0.050400,-0.099419,-0.022218,6.184000,63.0
20,IND,India,Indian Rupee,1999,8.463000,0.018220,4.669821,-0.005212,-0.014016,0.043531,...,-10.032102,0.011703,-0.026073,-0.022857,-0.018184,-0.004329,-0.024019,-0.025468,8.463000,86.0
21,IND,India,Indian Rupee,2000,3.975000,0.017838,4.009434,0.004469,-0.011311,0.043808,...,-1.132325,-0.008009,-0.052760,-0.007003,-0.006370,-0.060729,-0.047471,-0.024881,3.975000,41.0
22,IND,India,Indian Rupee,2001,4.944000,0.017438,3.779289,0.008110,-0.020530,0.049949,...,-3.627981,-0.026366,-0.056689,-0.013667,-0.021244,-0.041409,-0.066053,-0.037954,4.944000,50.0
23,IND,India,Indian Rupee,2002,3.907000,0.017039,4.297160,0.008945,-0.042768,0.030176,...,-1.417425,-0.006589,-0.056503,0.010513,0.014669,0.003929,-0.052138,-0.049207,3.907000,40.0
24,IND,India,Indian Rupee,2003,7.944000,0.016652,3.805866,0.010220,-0.014260,-0.041700,...,1.457045,0.072527,0.070368,0.068049,0.092783,0.113291,0.051080,0.018894,7.944000,81.0
25,IND,India,Indian Rupee,2004,7.849000,0.016284,3.767238,0.011032,-0.065614,-0.027195,...,-1.869947,0.053002,0.086684,0.065511,0.087538,0.053750,0.116882,0.077307,7.849000,80.0
26,IND,India,Indian Rupee,2005,9.285000,0.015923,4.246353,-0.008975,-0.025924,-0.026844,...,-2.203960,0.047061,-0.020539,0.042907,0.009240,0.049776,0.005761,-0.019922,9.285000,95.0
27,IND,India,Indian Rupee,2006,9.264000,0.015577,5.796516,-0.014616,-0.037970,0.027370,...,4.146212,0.035373,0.014385,0.053896,0.034312,0.050826,-0.032519,0.006624,9.264000,95.0
28,IND,India,Indian Rupee,2007,9.801000,0.015207,6.372881,-0.012709,-0.002566,-0.087370,...,-0.662455,0.130622,0.097250,0.170924,0.098637,0.075467,0.088029,0.079779,9.801000,100.0
29,IND,India,Indian Rupee,2008,6.013703,0.014757,8.349267,-0.010712,0.043023,0.052158,...,2.560328,0.000677,0.103498,0.037898,0.102812,0.079440,-0.021167,-0.107610,6.013703,61.0
30,IND,India,Indian Rupee,2009,4.701769,0.014206,10.882350,-0.007974,0.018861,0.112632,...,-0.900952,-0.052353,-0.081272,0.000161,-0.059148,-0.110411,-0.104797,-0.126488,4.701769,48.0
31,IND,India,Indian Rupee,2010,6.377626,0.013595,11.989390,-0.005369,-0.000465,-0.055355,...,3.576668,0.118745,0.067262,0.162277,0.035864,0.058451,0.060201,0.061474,6.377626,65.0
32,IND,India,Indian Rupee,2011,6.169784,0.012968,8.858361,-0.002660,0.002810,0.020659,...,-0.241803,0.031373,0.051464,0.048572,0.041912,0.057688,0.046285,-0.004046,6.169784,63.0
33,IND,India,Indian Rupee,2012,6.030051,0.012391,9.312446,-0.017225,-0.001126,0.144990,...,2.026501,-0.079003,-0.051365,-0.078201,-0.014858,-0.032542,-0.055971,-0.072460,6.030051,62.0
34,IND,India,Indian Rupee,2013,5.557264,0.011899,10.907640,0.017737,0.008968,0.096573,...,-0.083955,0.005785,0.000298,0.081144,0.037289,0.045635,-0.029470,-0.033451,5.557264,57.0
35,IND,India,Indian Rupee,2014,5.006668,0.011523,6.353195,-0.012964,-0.000523,0.041498,...,-0.146804,0.022496,0.019665,0.115143,0.017622,0.044393,0.014433,0.007264,5.006668,51.0
36,IND,India,Indian Rupee,2015,4.876322,0.011232,5.872427,-0.011893,-0.016322,0.051163,...,0.066051,-0.009829,-0.023410,0.081454,-0.088196,-0.104489,-0.033910,0.014187,4.876322,50.0
37,IND,India,Indian Rupee,2016,5.033069,0.010964,4.941027,-0.010254,0.020103,0.047438,...,-0.388348,-0.002899,-0.000481,0.098854,-0.009819,0.001580,-0.009982,-0.018257,5.033069,51.0
38,IND,India,Indian Rupee,2017,5.069786,0.010690,2.490887,-0.001969,0.008309,-0.030860,...,-0.349163,0.080693,0.065260,0.144193,0.021018,0.001887,0.087036,0.051854,5.069786,52.0
39,IND,India,Indian Rupee,2018,5.174292,0.010432,4.860700,-0.002430,0.000000,0.050310,...,1.354393,-0.008446,0.001625,-0.016725,0.046373,0.048705,-0.003372,-0.052542,5.174292,53.0
40,IND,India,Indian Rupee,2019,5.019288,0.010184,7.659695,0.003099,0.000000,0.029564,...,-0.170348,0.015769,-0.006184,0.009944,0.020876,0.015795,-0.010301,-0.019226,5.019288,51.0

In [34]:
df2.head()

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1,Percent_max
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN,NaN
1,IND,India,Indian Rupee,1980,5.281,0.023364,11.34606,0.007102,0.038942,-0.032347,...,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281,54.0
2,IND,India,Indian Rupee,1981,6.006,0.023510,13.11255,0.004508,-0.027032,0.101181,...,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006,61.0
3,IND,India,Indian Rupee,1982,3.476,0.023560,7.89075,0.004125,-0.013325,0.092003,...,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476,35.0
4,IND,India,Indian Rupee,1983,7.289,0.023475,11.86807,0.003785,0.016143,0.068086,...,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289,74.0

In [35]:
df2 = df2.drop('Percent_max',axis = 1)

In [36]:
df2.head()

,countrycode,country,currency_unit,year,GDP,net population growth,CPI,employment rate,labsh,xr,...,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k,GDP.1
0,IND,India,Indian Rupee,1979,NaN,682.995354,NaN,256.839111,0.709059,8.125791,...,-0.027104,-0.063782,0.190954,0.224667,0.074652,0.292258,0.374884,0.140270,0.623519,NaN
1,IND,India,Indian Rupee,1980,5.281,0.023364,11.34606,0.007102,0.038942,-0.032347,...,0.311639,-0.235969,0.221119,0.115094,0.211470,0.029731,0.119947,0.198038,0.040884,5.281
2,IND,India,Indian Rupee,1981,6.006,0.023510,13.11255,0.004508,-0.027032,0.101181,...,0.171218,-0.391245,0.024342,0.200461,0.124758,0.062000,-0.101080,0.141719,0.044442,6.006
3,IND,India,Indian Rupee,1982,3.476,0.023560,7.89075,0.004125,-0.013325,0.092003,...,-0.227116,0.640088,0.022520,0.062986,0.090714,0.009650,-0.020343,0.142196,0.070686,3.476
4,IND,India,Indian Rupee,1983,7.289,0.023475,11.86807,0.003785,0.016143,0.068086,...,0.568956,-0.435581,0.036162,0.053462,0.145769,0.073353,-0.117499,0.109214,-0.044686,7.289

In [37]:
df2.sort_values

AttributeError: module 'pandas' has no attribute 'sort_by'